# Generated by Django 2.2.2 on 2019-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190630_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.URLField(max_length=10000),
        ),
    ]
